### ISSUE TITLE
Missing SOFT LEAD Company in Scraper UI

### ISSUE THREAD

**Issue by SimonaNemtanu** [peviitor-ro/JobsScrapers#235]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10 Pro

STEPS TO REPRODUCE:

Open the URL https://scrapers.peviitor.ro/
Write "Soft Lead" in the search bar

EXPECTED RESULTS:
The company "Soft Lead" should be found and displayed in the search results when entered in the search bar.

ACTUAL RESULTS:
The company "Soft Lead" is not found or displayed in the search results.

**Comment by RaresCode** [comment]
Fixed, can you retest in validator?

**Comment by SimonaNemtanu** [comment]
Still not found
![image](https://github.com/user-attachments/assets/a6d12498-cf03-487e-83a5-0bd173656a17)

![image](https://github.com/user-attachments/assets/3d52baa2-af92-48e0-b155-3315ef1f55f0)
